### ISSUE TITLE
robot_helpers.ros.robotiq_gripper cannot be found

### ISSUE THREAD

**Issue by ZJU-PLP** [Ginga-Kennis/vgn_ur5e#1]
@Ginga-Kennis
Hi, Ginga-Kennis:

Thanks sharing so nice work of vgn_ur5e. When I implemente your published code, I cannot find the `from robot_helpers.ros.robotiq_gripper import GripperController`. 

Would you mind sharing the **robot_helpers** project in your improvement?

**Comment by Ginga-Kennis** [comment]
Hi @ZJU-PLP 
https://github.com/Ginga-Kennis/robot_helpers
This is the link for my robot_helpers.
However, **from robot_helpers.ros.robotiq_gripper import GripperController** is needed because I use a robotiq gripper. 
If you are using a different gripper, you have to change the code a little bit.

**Comment by ZJU-PLP** [comment]
> Hi @ZJU-PLP https://github.com/Ginga-Kennis/robot_helpers This is the link for my robot_helpers. However, **from robot_helpers.ros.robotiq_gripper import GripperController** is needed because I use a robotiq gripper. If you are using a different gripper, you have to change the code a little bit.

Ok, thanks a lot.
